### ISSUE TITLE
New "Password:" prompt

### ISSUE THREAD

**Issue by idkjs** [xxh/xxh#106]
I now connect via ssh like so where I am prompted for a password:

```sh
> ssh mini
Password:
Last login: Sat Dec  5 11:32:37 2020 from 82.124.42.159

> administrator@9404.local  12:27:44 
>
```

Running with `xxh` I get the following result:

```
> cat ~/.config/xxh/config.xxhc

hosts:
  mini:                     # settings for myhost
    +s: xxh-shell-fish           # use fish shell

> xxh mini
Probably the connection takes more time than expected.
Try to increase the timeout by adding "++pexpect-timeout 10" argument.
Answer from host is empty. Try again with +v or +vv or try ssh before xxh.
>
```

What do I need to do to connect here? Thanks for sharing this project.

**Comment by anki-code** [comment]
Hi @idkjs! The experience should be the same.

In your log I see the `Password:` line for prompt. But the more common line is the `user@host's password:` line that is supported in xxh:

https://github.com/xxh/xxh/blob/e66f0a306da8e8765f766711dd8053843da95471/xxh_xxh/xxh.py#L106-L107

https://github.com/xxh/xxh/blob/e66f0a306da8e8765f766711dd8053843da95471/xxh_xxh/xxh.py#L155-L157

What is your OS and ssh client?

**Comment by idkjs** [comment]
```
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29
```

**Comment by anki-code** [comment]
Thanks! I'm not the Mac user and PR is very welcome!

Setting up the dev environment takes 5 minutes:
```bash
# First of all fork xxh
GITHUBER='idkjs'
mkdir ~/git && cd ~/git
git clone https://github.com/$GITHUBER/xxh
cd xxh

# Make changes to xxh_xxh/xxh.py (I pointed out to the appropriate code above) 
# and update your package:
pip install -U .

# Try changes:
xxh mini
```

**Comment by idkjs** [comment]
Dont use python but gave it a shot but not going anywhere yet.

Made these changes to [xxh.py](https://github.com/idkjs/xxh/blob/043d414/xxh_xxh/xxh.py#L106-L107)
```
patterns = ['Are you sure you want to continue connecting.*', "Please type 'yes' or 'no':",
                    'Enter passphrase for key.*', 'Password:', 'password:', pexpect.EOF, '[$#~]', 'Last login.*']
```

This `~/.config/xxh/config.xxhc`

```
~/g/xxh (master) [1]> cat ~/.config/xxh/config.xxhc
hosts:
   mini:
     +s: xxh-shell-fish           # use fish shell

~/g/xxh (master)> which xxh-shell-fish
~/g/xxh (master) [1]> xxh +I xxh-shell-fish
Package exists, skip install: /Users/mandalarian/.xxh/.xxh/shells/xxh-shell-fish

```
This is `mini` in `~/.ssh/config`
```
```bash
Host mini
	User adminuser
	HostName 207.207.07.207
	#SCEPassword XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX
	#SCETerminal com.googlecode.iterm2
```

```
After compiling with `pip install -U .` and running with `./xxh mini` it just kinda hangs.

I then installed with `pipx install .` to see if that would make a difference, it did not.

Then I tried a bunch of combinations from the README which got some errors maybe you know what to do with. All these attempts

```
~/g/xxh (master) [1]> xxh mini +v +s fish
Load xxh config from /Users/mandalarian/.config/xxh/config.xxhc
Load xxh config for host mini
Final arguments list: ['+s', 'xxh-shell-fish', 'mini', '+v', '+s', 'fish']
ssh arguments: ['-o', 'StrictHostKeyChecking=accept-new']
^CUnknown answer from host. Check your connection to the host using ssh
and if it works try xxh with +vv argument.
Answer from host is empty. Try again with +v or +vv or try ssh before xxh.
[I] mandalarian@mandalarian ~/g/xxh (master) [1]> xxh mini +v
Load xxh config from /Users/mandalarian/.config/xxh/config.xxhc
Load xxh config for host mini
Final arguments list: ['+s', 'xxh-shell-fish', 'mini', '+v']
ssh arguments: ['-o', 'StrictHostKeyChecking=accept-new']
^CUnknown answer from host. Check your connection to the host using ssh
and if it works try xxh with +vv argument.
Answer from host is empty. Try again with +v or +vv or try ssh before xxh.
[I] mandalarian@mandalarian ~/g/xxh (master) [1]> xxh +v mini
Load xxh config from /Users/mandalarian/.config/xxh/config.xxhc
Load xxh config for host mini
Final arguments list: ['+s', 'xxh-shell-fish', '+v', 'mini']
ssh arguments: ['-o', 'StrictHostKeyChecking=accept-new']
^CUnknown answer from host. Check your connection to the host using ssh
and if it works try xxh with +vv argument.
Answer from host is empty. Try again with +v or +vv or try ssh before xxh.
[I] mandalarian@mandalarian ~/g/xxh (master) [1]> xxh mini
^CUnknown answer from host. Check your connection to the host using ssh
and if it works try xxh with +vv argument.
Answer from host is empty. Try again with +v or +vv or try ssh before xxh.
```

Thoughts?

**Comment by idkjs** [comment]
I tried changing hosts config to this. Doesnt help.

```
hosts:
   ".*":
     +s: fish           # use fish shell

```

**Comment by anki-code** [comment]
> Made these changes to xxh.py

Good start! After adding new item to the array change the item numbers in the conditions:

Here should be `[3,4]`:
https://github.com/xxh/xxh/blob/e66f0a306da8e8765f766711dd8053843da95471/xxh_xxh/xxh.py#L155

Then `5` here:
https://github.com/xxh/xxh/blob/e66f0a306da8e8765f766711dd8053843da95471/xxh_xxh/xxh.py#L164

And `[6,7]` here:
https://github.com/xxh/xxh/blob/e66f0a306da8e8765f766711dd8053843da95471/xxh_xxh/xxh.py#L179

**Comment by idkjs** [comment]
Alright then. So I made the changes here fe4140875c4dc86d77eebdc821e4ba1212d95a04 then ran
```
pip install -U .
pipx install .
```
. This is where we are:

```python
[I] mandalarian@mandalarian ~/g/xxh (master) [2]> pip install -U .
Processing /Users/mandalarian/git/xxh
Requirement already satisfied: pexpect>=4.8.0 in /usr/local/lib/python3.9/site-packages (from xxh-xxh==0.8.6) (4.8.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/site-packages (from xxh-xxh==0.8.6) (5.3.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.9/site-packages (from pexpect>=4.8.0->xxh-xxh==0.8.6) (0.6.0)
Building wheels for collected packages: xxh-xxh
  Building wheel for xxh-xxh (setup.py) ... done
  Created wheel for xxh-xxh: filename=xxh_xxh-0.8.6-py3-none-any.whl size=25789 sha256=f4c9eabe79d316d4c41496c6b7d61cce0dc6db3a761d12f791136342d806bf57
  Stored in directory: /private/var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/pip-ephem-wheel-cache-ebqokv4c/wheels/6d/f7/ca/c4f65e30dfed9a75758e553002455516b9d7160d22fb8971bf
Successfully built xxh-xxh
Installing collected packages: xxh-xxh
  Attempting uninstall: xxh-xxh
    Found existing installation: xxh-xxh 0.8.6
    Uninstalling xxh-xxh-0.8.6:
      Successfully uninstalled xxh-xxh-0.8.6
Successfully installed xxh-xxh-0.8.6
[I] mandalarian@mandalarian ~/g/xxh (master)> pipx install .
'xxh-xxh' already seems to be installed. Not modifying existing installation in '/Users/mandalarian/.local/pipx/venvs/xxh-xxh'. Pass '--force' to force installation.
[I] mandalarian@mandalarian ~/g/xxh (master)> pipx install . -f
Installing to existing directory '/Users/mandalarian/.local/pipx/venvs/xxh-xxh'
⚠️  Note: xxh was already on your PATH at ./xxh
⚠️  Note: xxh.bash was already on your PATH at /usr/local/bin/xxh.bash
⚠️  Note: xxh.xsh was already on your PATH at /usr/local/bin/xxh.xsh
⚠️  Note: xxh.zsh was already on your PATH at /usr/local/bin/xxh.zsh
  installed package xxh-xxh 0.8.6, Python 3.9.1
  These apps are now globally available
    - xxh
    - xxh.bash
    - xxh.xsh
    - xxh.zsh
done! ✨ 🌟 ✨
```

Now lets try it:
```
[I] mandalarian@mandalarian ~/g/xxh (master)> xxh mini
mini:/Users/administrator/.xxh/.xxh/shells/xxh-shell-fish not found. Install xxh-shell-fish? [Y/n] y
Install xxh-shell-fish to mini:/Users/administrator/.xxh
First time upload using rsync (this will be omitted on the next connections)
First run xxh-shell-fish on mini
/Users/administrator/.xxh/.xxh/shells/xxh-shell-fish/build/entrypoint.sh: line 122: getent: command not found
/Users/administrator/.xxh/.xxh/shells/xxh-shell-fish/build/fish-portable/bin/fish.sh: line 5: /Users/administrator/.xxh/.xxh/shells/xxh-shell-fish/build/fish-portable/bin/fish: cannot execute binary file
```

`getent` command fails because its not available on macos. So I forked xxh-shell-fish and [change getent to dscl -p ](https://github.com/idkjs/xxh-shell-fish/commit/01126a1753d6808cd3dd5bd1a6a907ff80d778ce)

Then remove original `xxh-shell-fish` and install my fork with:

```
xxh +R xxh-shell-fish
xxh +I xxh-shell-fish+git+https://github.com/idkjs/xxh-shell-fish 
```

And now we get the expected password prompt 🚀!

```
[I] mandalarian@mandalarian ~/g/xxh (master)> xxh mini
mini:/Users/administrator/.xxh/.xxh/shells/xxh-shell-fish not found. Install xxh-shell-fish? [Y/n] y
Install xxh-shell-fish to mini:/Users/administrator/.xxh
First time upload using rsync (this will be omitted on the next connections)
First run xxh-shell-fish on mini
Password:
/Users/administrator/.xxh/.xxh/shells/xxh-shell-fish/build/fish-portable/bin/fish.sh: line 5: /Users/administrator/.xxh/.xxh/shells/xxh-shell-fish/build/fish-portable/bin/fish: cannot execute binary file
```

But as you can see, idkjs/xxh-shell-fish fails because it trying to run a linux binary. I guess the question is how do we build a macos binary for xxh-shell-fish.

After we do that, I can make the changes and pull them to xxh-shell-fish.

Idea on what is next?

Thanks for teaching.

**Comment by anki-code** [comment]
Great to see steps forward!

> And now we get the expected password prompt rocket!

Excellent! Please create a Pull Request to xxh repo with the fix.

> getent command fails because its not available on macos.

Yeah, there is an issue about this and I've created a simple fallback for this (https://github.com/xxh/xxh-shell-fish/commit/9d06d2b879d1adc104251709e2b28c9c4f1bbfe6). Now you can avoid using the fork.

> But as you can see, idkjs/xxh-shell-fish fails because it trying to run a linux binary.

Correct, xxh is using [fish-portable](https://github.com/xxh/fish-portable) for linux. You can try to repeat [build steps](https://github.com/xxh/fish-portable/blob/master/fish-portable-musl-alpine.Dockerfile) on Mac (or best to create Dockerfile for Mac if it's possible) but I don't know how much effort and time it should takes. May be the consultation of [fish-shell developers](https://github.com/fish-shell/fish-shell) is needed.

**Comment by idkjs** [comment]
So that was fun. Got me thinking about python. 

Having said that, I still cant use this.

If `pipx install xxh_xxh` then `xxh mini` I am getting this error where its not recognizing the `github/schniz/fnm` node manager

```
fish: Unknown command: fnm

/.config/fish/conf.d/fnm.fish (line 1):
fnm env | source
^
from sourcing file ~/.config/fish/conf.d/fnm.fish
	called on line 294 of file /usr/local/Cellar/fish/3.1.2/share/fish/config.fish
from sourcing file /usr/local/Cellar/fish/3.1.2/share/fish/config.fish
	called during startup
🔒 Login keychain locked. Unable to read github access token🔒 Login keychain locked. Unable to read github access tokenxxh_home_realpath=/Users/administrator/.xxh
xxh_version=0.8.6
xxh_shell_exists=1
xxh_home_writable=1
xxh_parent_home_writable=1
rsync=/usr/bin/rsync
scp=/usr/bin/scp
shell=/usr/local/bin/fish
kernel=Darwin
arch=x86_64
Unexpected output. Try again with +v or +vv or try ssh before xxh.
```

fnm is working on the remote machine so something above my paygrade going on here.

Also need to see what is going on with keychain but not the issue i dont think.

**Comment by anki-code** [comment]
The error is interesting but sorry I can't help with diving in because I'm not the Mac user.
