### ISSUE TITLE
Ability to create xxh plugin that sync local file(s) to remote host every connection

### ISSUE THREAD

**Issue by soraxas** [xxh/xxh#110]
Currently, the plugin systemin xxh seems to be building once and copy the build folder to remote host. For functionality such as vimrc, any further changes made to the vimrc file in the plugin folder (e.g. when it is hardlinked to `~/.vimrc`) will not be reflected on remote host when connected.

It would be great for some plugins to always execute some `prerun.sh` script on local (should be named as something else), to facilitate some action that you always want to execute on local machine. For example, an action that rsync vimrc to remote host everytime you execute `xxh yourhost` (i.e. even without +RI), because there are some files that you always want to keep in-sync.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by frederickjh** [comment]
@anki-code Isn't this already possible by adding the right configuration for the plugin @soraxas wants to reinstall each time to the `~/.config/xxh/config.xxhc` configuration file?

**Comment by anki-code** [comment]
@frederickjh you mean 
1. add a plugin that will build themself by copying files from local to build directory
2. then add the `+RI` of this plugin to the config
3. finally this plugin should have prerun script that will update the files on remote host
?
Yeah, it's possible this way :)

**Comment by anki-code** [comment]
This could be solved by using plugins. Closed for now.
