### ISSUE TITLE
 screen

### ISSUE THREAD

**Issue by c1au6i0** [xxh/xxh#119]
Hello, does `xxh` supports in someway the use of `screen` on the host so that all the themes and plugins are retained in new screen sessions?

**Comment by anki-code** [comment]
Hi @c1au6i0! Yep, try to use [xxh-plugin-prerun-core](https://github.com/xxh/xxh-plugin-prerun-core).
```python
xxh +I xxh-plugin-prerun-core
xxh myhost +if
xxh-screen
```

**Comment by julibeg** [comment]
great! does this work with tmux as well?

**Comment by anki-code** [comment]
Hi @julibeg! It will be great to add tmux support to [xxh-plugin-prerun-core](https://github.com/xxh/xxh-plugin-prerun-core). Just add the script `xxh-tmux` or something like this.

**Comment by julibeg** [comment]
Hi @anki-code! I'm not sure if I quite understand this right. You mean a simple script equivalent to `xxh-screen` in `xxh-plugin-prerun-core` that calls `entrypoint.sh` when starting tmux?

**Comment by anki-code** [comment]
@julibeg Sorry but I'm not the user of tmux and I'm not sure that I clearly understand your needs. My thought was you can create the script to run tmux like executable [`xxh-screen` script](https://github.com/xxh/xxh-plugin-prerun-core/blob/master/xxh-screen).

**Comment by julibeg** [comment]
ok, I will give it a try

**Comment by julibeg** [comment]
I see. I opened a PR.
