### ISSUE TITLE
`base64 --wrap=0` does not work on Mac

### ISSUE THREAD

**Issue by zaphod72** [xxh/xxh#123]
Mac OS does not have the `--wrap` option
https://github.com/xxh/xxh/blob/5b94be34650ee9159c92432f1c2506ae98abc232/xxh/xxh_xxh/xxh.zsh#L23-L25

**Comment by anki-code** [comment]
Hi! Nice catch! PR is welcome!

**Comment by Moulick** [comment]
Fix added in #124
