### ISSUE TITLE
Nested `.xxh` directory

### ISSUE THREAD

**Issue by izissise** [xxh/xxh#126]
**Local OS (where xxh is installed):** Linux
**Destination host OS:** Linux
**xxh version:** 0.8.8
**xxh-plugins installed:** None

**Steps to Reproduce**
1. I run `xxh` for the first time 
2. xxh create in my home this directory structure  `~/.xxh/.xxh/plugins`
3. Is the nested `.xxh` directory is an intended behavior?

From what I've seen in https://github.com/xxh/xxh/tree/master/xxh/xxh_xxh, this behavior exists for any local shells

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @izissise! Yes it's intended to support [inplace xxh](https://github.com/xxh/xxh#using-xxh-inplace-without-ssh-connection) and xxh chains (xxh to host and then use xxh).
