### ISSUE TITLE
Implementation of ssh -J option equivalent

### ISSUE THREAD

**Issue by tpongo-afk** [xxh/xxh#135]
**Is your feature request related to a problem? Please describe.**
I would have expected the `xxh host2 -J host1` command to work similarly as for ssh, that is to be able to connect to host2 using an intermediate jumphost host1. However the -J option is unrecognized in xxh.

**Describe the solution you'd like**
Simple implementation of the -J option with the same functionality as in ssh.

**Describe alternatives you've considered**
The following command `xxh host2 -o ProxyCommand="ssh -W %h:%p host1"` or inserting the following line below the host2 configuration in the ~/.ssh/config file also works: `ProxyCommand ssh -W %h:%p host1`.

Since there are alternatives, I recognize that this is not a priority feature but maybe easy to implement.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
PR is welcome!

The start point is the implementation of the SSH arguments:

https://github.com/xxh/xxh/blob/c8c5d0c51a505c983f1a8b9b5ff3a96d401db29a/xxh/xxh_xxh/xxh.py#L561-L564

**Comment by tpongo-afk** [comment]
I was reading the docs of argparse and then I found the `parse_known_args()` function.
I'm wondering, would it be possible to pass all the unkown arguments to the ssh command? Something like this:
```
opt, ssh_args = argp.parse_known_args()  # There are two lines of this
...
self.ssh_arguments += ssh_args
```
This would make all the ssh options available to the user but I don't know if there is an unknown and unwanted effect.

**Comment by anki-code** [comment]
I prefer to implementing special support for every new argument. May be some day we will make the common solution.

**Comment by tpongo-afk** [comment]
Thanks a lot! I really appreciate your work, as I use xxh daily.
