### ISSUE TITLE
xxh teams

### ISSUE THREAD

**Issue by anki-code** [xxh/xxh#50]
Hello!

In xxh project we have teams. If you're in team it does not oblige to do something. The main goal of teams is to create group of passionate people who could help or support in complex questions. Some people could be expert in one shell and newbie in another shell and mutual assistance is the key to xxh evolution.

Teams: @xxh/core @xxh/xonsh @xxh/zsh @xxh/fish

If you want to be in this teams or create a new one just ask here ⬇️

**Comment by zarazaz12** [comment]
can i join
