### ISSUE TITLE
Support for XDG Base Directory Specification

### ISSUE THREAD

**Issue by ammgws** [xxh/xxh#57]
It would be nice if config file was stored under $XDG_CONFIG_HOME (which defaults to ~/.config). I was thinking about looking into implementing it, but no point if you are not interested.

This [blog post](https://ploum.net/207-modify-your-application-to-use-xdg-folders/) lists the advantages of using the XDG Base Directory Specification as follows:

-   $HOME is a lot less cluttered.
    Backups are a lot more safer and easier. (you know that backuping your $XDG_DATA_HOME along with your files is enough)
-    A lot easier to reset a default configuration if you want/need it (and without any risk of loosing information).
-    Avoid some strange bugs that happen because you had a old version of some configuration file.
-    It is a lot more flexible and portable because no paths are hard-coded. You can use the XDG library that does the job for you or, if you don’t want the dependency, implementing the XDG specification is only a few lines of code.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @ammgws! Looks good! PR is welcome!
Default path for config file is in `self.config_file`.

**Comment by anki-code** [comment]
Released in xxh 0.7.4. Thank you!

Note you need to move your current config to `~/.config/xxh/config.xxhc`.
