### ISSUE TITLE
Check that host has target shell before shell uploading and use it without upload

### ISSUE THREAD

**Issue by anki-code** [xxh/xxh#58]
**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mukul-mehta** [comment]
Is the issue open, I'd like to work on it?

**Comment by anki-code** [comment]
Hi @mukul-mehta !

I lost confidence in the need for this feature a little.  The main reasons are:
* the shell version on the host could be different than version where xxh-shell was tested (unstable consequencies)
* we should have different pack of files in build directory when we use shell on the host so in short we should support this scenario in xxh shells (increase complexity)
* in case of using shell from host we can omit architecture dependency but other xxh packages still could be different (unstable consequencies)

As result it's increase complexity but for what? To just reduce couple megabytes? It not looks like a big deal.

Could you please tell about your use case for this feature and what you planed to do?

May be the simpliest way to do what you need is to just fork your xxh shell, reduce downloading the portable shell and change the entrypoint run command from local `./shell` to `shell`. The xxh-shell-bash is working this way.

**Comment by mukul-mehta** [comment]
True, saving some data transfer will increase complexity multiple times. 
I'll check out the xxh-shell-bash method soon.

**Comment by anki-code** [comment]
So I'm going to close this until new info or use cases.
