### ISSUE TITLE
Using xxh home as $HOME

### ISSUE THREAD

**Issue by anki-code** [xxh/xxh#64]
To discuss.

Default xxh home is `~/.xxh`.

Pros:
*  Some apps which use `$HOME` will save temporary or result files in xxh home

Cons:
* When careless using `+iff` all working files will be deleted. Probably solution: show big warning.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by frederickjh** [comment]
I think it would be wise for each terminal to have a hidden sub-directory for its configuration files, as we discussed in xxh/xxh-shell-fish#1 in this [comment](https://github.com/xxh/xxh-shell-fish/issues/1#issuecomment-604549343).

**Comment by frederickjh** [comment]
Is this something that is documentation, but that each of the shell packages will implement? Should it also be added to the example shell repository?

**Comment by frederickjh** [comment]
I have decided against adding a subfolder for each shell. If the shell normally puts its configuration in folders then they will be in the `~/.xxh` folder and the same goes for configuration files.

**Comment by anki-code** [comment]
In the xxh 0.7.0 the `$HOME` variable is `~/.xxh` by default. It makes xxh more hermetic.

If you want to stay at default `~/` on the host use `+hhh "~"` argument (you can add it to config `~/.xxh/.xxhc`).

**Comment by frederickjh** [comment]
@anki-code what do you mean by hermetic?

I am not sure I understand this decision to make `$HOME` the same as `$XXH_HOME` by default. I would leave $HOME alone and not change the users home directory.

I do understand the decision to make `XDG_CONFIG_HOME=$XXH_HOME/.config` by default, as this means all configuration files will end up inside `~/.xxh` and one can truly delete `~/.xxh` and it is as if xxh was never there.

**Comment by anki-code** [comment]
> what do you mean by hermetic?

By default xxh will not affect to user home on the host. 

Before 0.7.0:
* Run `xxh myhost +s bash-zero`
* `$HOME` is `/home/user` (default `$HOME`)
* Run bash commands and they will be in `/home/user/.bash_history`. In this case all bash history are mixed: commands ssh sessions and xxh sessions are in one `.bash_history` file. 
* Also any other apps you're using in xxh sessions will be write temporary and history data to user home. It's not hermetic.

After 0.7.0:
* Run `xxh myhost +s bash-zero`
* `$HOME` is `/home/user/.xxh` (`$HOME` is `$XXH_HOME`)
* Run bash commands and they will be in `/home/user/.xxh/.local/share/bash/.bash_history`.
* All apps writes the data to `/home/user/.xxh/`. It's hermetic.

If you want to stay on the fist logic. Just add `+hhh "~"` or add it to your `~/.config/xxh/config.xxhc`

**Comment by frederickjh** [comment]
@anki-code Does the Bash shell not honor [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)? I did a bit of a search and I believe that it does. Are there other shells that do not honor it?

If all the shells honor the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), then there is no need to set `$HOME` to `$XXH_HOME`. All that is needed is to set the XDG base directories.

Is this not something that could be decided per shell if `$HOME` gets set to `$XXH_HOME`?

Fish does honor the XDG Base Directory. I will be submitting a pull request to set  `$XDG_CACHE_HOME` for the fish shell but I think that we can leave `$XDG_RUNTIME_DIR` alone as there are a number of requirements that would need to be met and I think it in better to leave this to the OS.

**Comment by anki-code** [comment]
Hermetic principle says that if you delete `$XXH HOME` from the host then xxh has never been on the host.

When you tell about XDG you mean that we should allow shells or plugins to write to `~/.local`, `~/.config` directories. It's NO hermetic because after deleting `$XXH_HOME` directory you should go to `~/.local`, `~/.config` directories and clean and clean and clean all data from tools you're using in xxh. It's NO hermetic and this is the cause why by default `$HOME` is `$XXH_HOME`. If you want to allow tools to use your home XDG just set `+hhh "~"`.

**Comment by frederickjh** [comment]
> When you tell about XDG you mean that we should allow shells or plugins to write to `~/.local`, `~/.config` directories.

That is exactly the opposite of what I am saying. I am saying if all the shells honor the  XDG base directory specification then we should use it to set where programs store configuration, data and cache. This keeps the data in `$XXH_HOME` and out of `$HOME`.

In any case users will find it strange when they do `cd ~` (or just `cd` in Fish and find themselves in `/home/user/.xxh` instead of in `/home/user`. I do not think users will find this an expected feature to suddenly have `$HOME` in a hidden folder off of what was `$HOME`.

**Comment by anki-code** [comment]
> In any case users will find it strange when they do cd ~

I understand and this is the cause I created `+hhh` immediately with 0.7.0. My state is based on that user should expect hermetic behavior from xxh after reading the README. After he understand how xxh works he will want to set home as `~`. 

Thank you for your thoughts!
