### ISSUE TITLE
Support open ssh versions <7.6 

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh#67]
**Local OS (where xxh is installed): Ubuntu 16.04.6 LTS**
**xxh version: xxh/0.6.10**

**Steps to Reproduce**
1. Run `xxh +vv hostname`
<details><summary>2. The output log: CLICK to see collapsed text</summary>
<p>

```bash
$ xxh +vv hostname                                                                                                              203ms  [Die Mär 24 14:23:34]
Load xxh config from /home/username/.xxh/.xxhc
Load xxh config for host .*
ssh arguments: ['-o', 'StrictHostKeyChecking=accept-new']
Try pexpect command: bash -c 'cat /home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/xxh_xxh/host_info.sh | sed "s|_xxh_home_|~/.xxh|" | sed "s|_xxh_shell_|xxh-shell-fish-appimage|" | ssh -v -o StrictHostKeyChecking=accept-new hostname -T "bash -s"'
Pexpect caught pattern: <class 'pexpect.exceptions.EOF'>
Pexpect result:
{'user_host_accept': None, 'user_host_password': None, 'user_key_password': None, 'output': 'command-line line 0: unsupported option "accept-new".'}
Host info:
command-line line 0: unsupported option "accept-new".
Unknown answer from host when getting info
```

</p>
</details>
3. What is the problem
The **accept-new** option for **StrictHostKeyChecking** was not introduced until version 7.6 of Open SSH.  

Please consider adding logic to check the version of Open SSH and then if the version is lower than 7.6 set **StrictHostKeyChecking** to **yes**, otherwise set it to **accept-new**.

Changing **accept-new** to **yes** on [line 607 of xxh.py](https://github.com/xxh/xxh/blob/362594644e16ff82eecb2f0304a99723eff0169a/xxh_xxh/xxh.py#L607) allows xxh to start.

LTS versions of Ubuntu, and possibly other Linux distros, issue security patched versions of the older versions of OpenSSH in use in their supported releases. So, it makes sense to support these versions as well.

The following command will parse out the version of OpenSSH for my current version of **7.2p2**:
```bash
ssh -V 2>&1 | awk -F ' ' '{print $1}' | awk -F _ '{print $2}' | awk -F p '{print $1}'
```
The following string from my version of OpenSSH can be used to test parsing:
```
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
```
Thanks for considering this fix!
Frederick

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Thank you! The fix will be in 0.6.11
