### ISSUE TITLE
How to handle the user's shell configuration with xxh

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh#71]
Currently using xxh with the [xxh/xxh-shell-fish](https://github.com/xxh/xxh-shell-fish) repository I can get a working Fish shell on a remote host. I am looking now to add plugins for a Fish shell package managers [Fisher](https://github.com/jorgebucaran/fisher). Fisher and other Fish shell package manager store what packages have been installed  in the user's configuration. For Fisher this is by default in [`~/.config/fish/fishfile`](https://github.com/jorgebucaran/fisher#using-the-fishfile) and [`~/.config/fisher/`](https://github.com/jorgebucaran/fisher#changing-the-installation-prefix). Oh-my-fish another Fish shell package manager stores this by default in [`~/.config/omf/`](https://github.com/oh-my-fish/oh-my-fish/blob/d10bbe9f386c306bc707dfdccbbecb208c1bce38/bin/install#L19).

Both of these Fish shell package managers honor `$XDG_CONFIG_HOME` so with the current xxh code the configuration would be stored inside the `~/.xxh/` folder, aka `$XXH_HOME`, on the remote host.

The question I have is how to handle user configuration that the user just wants to be present when xxhing into a new host. In the case of the package manager what packages would be installed by default.  I currently have two possibilities in mind for handling user configuration.

1. A generic plugin, in that it works for all shells, that transfers user config from the local host to the xxh remote host.
2. The user must write a custom plugin with their configuration.

I believe the first option would encourage broader adoption of xxh as it would make it easier to on-board new users.

If the users configuration was confined to a single directory on the local host which contained nothing else, the plugin could simply copy all configuration to the remote for all shells and plugins that the user wishes to setup. I am thinking that user configuration for remote host could be stored on the local host in a folder something like, `~./xxh/user-remote-host-config/` and use the same directory structure that would be expected on the remote host in `$XDG_CONFIG_HOME`.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
1. Am I right you mean that you can just copy some files from local XDG directories to the host XDG directories?

2. I've made a try to add Oh My Fish here - https://github.com/xxh/xxh-plugin-fish-ohmyfish - and I've faced with unexpected OMF behavior (the link is in readme).

**Comment by frederickjh** [comment]
> * Am I right you mean that you can just copy some files from local XDG directories to the host XDG directories?
> 

Actually, I am wanting to setup configuration separate from the local `$XDG_CONFIG_HOME` that will be copied to the remote host's `$XDG_CONFIG_HOME` directory

> * I've made a try to add Oh My Fish here - https://github.com/xxh/xxh-plugin-fish-ohmyfish - and I've faced with unexpected OMF behavior (the link is in readme).

I would have to look into how OMF handles this to know for sure.  Fisher has the `fishfile` that list one per line the packages to install. All one needs to do is run `fisher` and it will update the installation.

**Comment by anki-code** [comment]
I'm going to close this issue because no cases and questions I see in the text and it looks like you create xxh-plugin-fish-fisher successfully.

**Comment by frederickjh** [comment]
Yes, I went with number 1. above when I created  the xxh-plugin-fish-userconfig plugin.
