### ISSUE TITLE
Write documentation in wiki

### ISSUE THREAD

**Issue by anki-code** [xxh/xxh#75]
Current wiki page: https://github.com/xxh/xxh/wiki

If you're going to like this issue please write down your questions below.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by frederickjh** [comment]
Will this wiki documentation be for users or developer of `xxh`, or both?

**Comment by anki-code** [comment]
I'm waiting for feedback first in this issue.

**Comment by anki-code** [comment]
I've consolidate common questions in wiki. It's a good start to the more detailed manual.

**Comment by frogerbytes-create** [comment]
can I / we get an explanation about how to use this app to from a x86_arm64 (I hope I got that right) to an arm based system. I see there is an app image  for arm, but not sure how to use xxh from one system type to another.
