### ISSUE TITLE
What is pluginrc.* run order?

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh#76]
Hi!
This is a developer question about how `xxh` works  so I know what to expect. 

Currently when I xxh into a remote computer I have `xxh-shell-fish` `xxh-plugin-fish-fisher` and `xxh-plugin-fish-userconfig` set to install and all these packages get installed but `fisher` does not run and install the list of  packages during the first login that was uploaded by the `xxh-plugin-fish-userconfig` plugin.

If I log out and xxh in again then `fisher` will run and install the packages. I believe what is happening is that `xxh-plugin-fish-fisher`  is being installed and its `pluginrc.*` file is run. Then after that `xxh-plugin-fish-userconfig` is installed and its `pluginrc.*` file is run.

1. In what order does xxh install plugins?
2. Does it run the plugin's `pluginrc.*` file immediately after it installs the plugin or does it install all plugins then run all the  `pluginrc.*` files?
3. Is the order of install random or alphabetical or something else?
4. Does `xxh` need a way to set the order that the `pluginrc.*` files get run?

Thanks in advance for any information your can provide about this!
Frederick

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
> 1. In what order does xxh install plugins?

Plugins has no install phase. The `xxh +I xxh-plugin-...` command builds the plugin in `build` directory. Then xxh upload the build directory to the host and the xxh-shell do `source` pluginrc file. So what you called "install" is looks like the action of `source` the pluginrc file.

> 2. Does it run the plugin's pluginrc.* file immediately after it installs the plugin or does it install all plugins then run all the pluginrc.* files?

When you run `xxh myhost` the pluginrc files will be run every time. The initialization will be according the algo in the shell RC file.

> 3. Is the order of install random or alphabetical or something else?
> 4. Does xxh need a way to set the order that the pluginrc.* files get run?

As I understand you faced with the need to set plugins order. I've made [the commit in fish shell](https://github.com/xxh/xxh-shell-fish/commit/3ba8be814eb8aecb765a7e7648adc5b9a49a8a8e) that allows you to do that.

After this commit the order of initialization fish plugins can be changed by setting the prefix of `pluginrc.fish` file. For example you have three plugins A B C and you want to run C A first. Rename pluginrc.fish files:
* `xxh-plugin-fish-C/001-pluginrc.fish` (will be the first)
* `xxh-plugin-fish-A/002-pluginrc.fish` (will be the second)
* `xxh-plugin-fish-B/pluginrc.fish` (leave default)

**Comment by frederickjh** [comment]
> Pluginrc files run on host every time you do `xxh myhost`. The initialization will be according the algo in the shell RC file.

I do not understand the word **algo**.

**Comment by frederickjh** [comment]
> After this commit the order of initialization fish plugins can be changed by setting the prefix of `pluginrc.fish` file. For example you have three plugins A B C and you want to run C A first. Rename `pluginrc.fish` files:
> 
>     * `xxh-plugin-fish-C/090-pluginrc.fish` (will be the first)
> 
>     * `xxh-plugin-fish-A/091-pluginrc.fish` (will be the second)
> 
>     * `xxh-plugin-fish-B/pluginrc.fish` (leave default)

:ok_hand: I will have to give this a go. I think I just need to set the `xxh-plugin-fish-userconfig´ to be sourced first.

**Comment by anki-code** [comment]
> I do not understand the word algo.

Algorithm :)

**Comment by frederickjh** [comment]
@anki-code I finally got back to this I was trying to implement  xxh/xxh-plugin-fish-userconfig#3, but this does not seem to be working or I am not understanding the changes required in `build.sh`. I have created a branch with my test in it that does not work. The userconfig plugin does not get installed. You can see my changes on  this commit xxh/xxh-plugin-fish-userconfig@252cd35.

**Comment by anki-code** [comment]
I've checked the plugin ordering by this way:
```bash
# create simple plugins
mkdir -p /home/user/.xxh/.xxh/plugins/xxh-plugin-fish-test1/build
mkdir -p /home/user/.xxh/.xxh/plugins/xxh-plugin-fish-test2/build
echo 'echo 1' > /home/user/.xxh/.xxh/plugins/xxh-plugin-fish-test1/build/pluginrc.fish
echo 'echo 2' > /home/user/.xxh/.xxh/plugins/xxh-plugin-fish-test2/build/010-pluginrc.fish
# So we will expect that plugin test2 will be initialized before plugin test1

xxh myhost +s fish +if
2
1
myhost@ip ~> 

xxh myhost +s fish +if
2
1
myhost@ip ~> 

# Great! The order is right
```

Please read [Detailed workflow with code](https://github.com/xxh/xxh/wiki#detailed-workflow-with-code) to understand the xxh algorithm.

**Comment by frederickjh** [comment]
OK, let try this again. 
> Don't forget to make changes in build.sh for C and A.

What changes need to be made to build.sh?
Are the changes I made in xxh/xxh-plugin-fish-userconfig@252cd35 correct? I changed `pluginrc.fish` to `010-pluginrc.fish` in `build.sh so it should be copied. Or is there something else that needs changed for this to work.

The problem I am having is the plugin to which I added the numbers at the beginning `pluginrc.fish` file, of the `build.sh` does not seem to be running.

**Comment by anki-code** [comment]
> Are the changes I made in xxh/xxh-plugin-fish-userconfig@252cd35 correct?

Yes. This should be enough.

> The problem I am having is the plugin to which I added the numbers at the beginning pluginrc.fish file, of the build.sh does not seem to be running.

Please check your `xxh-shell-fish` version in `~/.xxh/.xxh/shells/xxh-shell-fish/xxh-config.fish`. The `xxh-config.fish` file should have https://github.com/xxh/xxh-shell-fish/blob/master/xxh-config.fish#L7:
```
... -name '*pluginrc.fish' -printf ...
```
