### ISSUE TITLE
macOS as target host

### ISSUE THREAD

**Issue by pythoninthegrass** [xxh/xxh#81]
**Local OS (where xxh is installed):** macOS 10.14.6
**Destination host OS:** 10.14.6 (local), 10.15.6 (remote)
**xxh version:** xxh/0.8.2
**xxh-plugins installed:** N/A (attempting `xxh-shell-bash`)

**Steps to Reproduce**
1. I run `xxh local +s bash`
2. The output log:
```
$ xxh local +s bash
...
First run xxh-shell-bash on local
bash: cd: too many arguments
...
readlink: illegal option -- f
...
mkdir: /.local/share/bash: Permission denied
```
3. What is the problem
Appears that using `xxh <host>` doesn't pull from ~/.ssh/config. Attempted the bash setup on localhost and it doesn't play nice with env vars and likely Appleisms on the Darwin platform.

Think that especially that last line should be expanding `$HOME` per issue #64. 

FWIW installed via `brew install xxh` and running `GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)` 

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by pythoninthegrass** [comment]
_Correction_
> Destination host OS: 10.14.6 (local), **10.15.4** (remote)

**Comment by anki-code** [comment]
Hello @pythoninthegrass! Thank you for the reporting this. There is a lack of MacOS testing. I'm going to do it more detailed and back to you.

**Comment by pythoninthegrass** [comment]
You're welcome! Let me know if you need me to test anything.

**Comment by anki-code** [comment]
I've fixed the `readlink -f` error by removing  `readlink` and `realpath` in the host info script. Now you can update xxh from master and try `xxh local +s bash`:
```
pip3 install -U xxh-xxh
xxh local +s bash
```
But if you try `+s xonsh` or another shells it is not working because current xxh packages support Linux. So you can do `xxh linux_host` from MacOS but can't `xxh mac_host`.

#73

**Comment by pythoninthegrass** [comment]
No dice. I'll take a look at the source code this weekend and see if I can make some changes to the `cd`, `readlink` and interpolation of the `$HOME` directory lines.

Thanks again for making this. Super cool concept and looking forward to using it!
[xxh_stdout.log](https://github.com/xxh/xxh/files/4638922/xxh_stdout.log)

**Comment by anki-code** [comment]
> xxh_stdout.log

Ah, yes, in `xxh local` mode we should do `xxh local +s bash +iff` to update the packages too.

**Comment by pythoninthegrass** [comment]
> 
> 
> > xxh_stdout.log
> 
> Ah, yes, in `xxh local` mode we should do `xxh local +s bash +iff` to full update the packages.

This solved it. Have tried with both Mac to Mac and Mac to Linux. Thanks for your help, @anki-code .
