### ISSUE TITLE
Add option to install only missing plugins

### ISSUE THREAD

**Issue by soraxas** [xxh/xxh#86]
**Is your feature request related to a problem? Please describe.**
Currently you need to use `+if` everytime you want `xxh` to install new things in the remote server, which will delete all of the remote shell/plguins/existing build.

**Describe the solution you'd like**
After adding a new plugin in local you should be able to install only the missing plugins in the remote server, without first removing everything in remote.

It would be useful while developing as you can just remove the remote plugin folder, disconnect, and connect again to install the missing (and updated) plugin.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
This looks like the developer scenario. Am I right? If yes you can use [xxh-dev](https://github.com/xxh/xxh-dev) as full dockerized environment for development to avoid waiting for file transferring.

**Comment by soraxas** [comment]
Hi @anki-code thanks for your prompt response!

I haven't stumble upon the plugin you mentioned so thanks for suggesting it. But the use-case I mentioned was also as a normal user. 

When I first tried out `xxh`, on first connections it installed my fish shell. 
Afterwards, I want to test out some plugin so I installed the docker-rootless plugin with `+if` (AFAIK it's the only option that allows you to install additional plugins if it's not your first initialisation?). And since it's `+if` it removes everything and tries to pull fish and compiles it on the remote server again.
I found out docker-rootless doesn't work as my remote server does not has `newuidmap` available, so I removed the plugin locally (after removing locally you will also need to remove on remote server by yourself?). Afterwards, I want to test out another plugin, so once again, I'll need to remove everything, pull the fish source, compile it, and install everything else.

Don't get me wrong, the idea of `xxh` is amazing and seems very promising. After looking into the code in `xxh.py`, the logics in installation seems to be remove everything and starts again. It would be better if it is more like synchronising the plugin between the local and remote host (something like installing every missing plugin and *possibly removing every plugin that's no longer in local*) (the second part probably is not that important).

**Comment by anki-code** [comment]
You understand the process exactly right and this logic could be made. 

One moment. If xxh-shell or xxh-plugin was builded on the home host it will not be build again. So if you remove the plugin and do `+if` the xxh just upload the shell and plugins to the target host.

From my point of view after months of using and debuging xxh the more complex process with a bit win of effectiveness is not so needed. 10-30 megabytes of shell with plugins is not so big to reuploading. So I'm going to wait the community voices as emoji reaction on the first message.

And anytime PR is welcome.

**Comment by anki-code** [comment]
Because there is no strong community response I'm going to close this until new requests to reopen.
