### ISSUE TITLE
+hh option in config do nothing

### ISSUE THREAD

**Issue by onokatio** [xxh/xxh#89]
**Local OS (where xxh is installed):**
ArchLinux

**Destination host OS:**
Debian

**xxh version:**
0.8.3

**xxh-plugins installed:**
empty

**config**

```
hosts:
  ".*":
    +hh: "/tmp/xxh"
    +s: zsh
```

**Steps to Reproduce**
1. I run `xxh server +vv` with above config.
2. The output log:

```
server:/home/myuser/.xxh/.xxh/shells/xxh-shell-zsh not found. Install xxh-shell-zsh? [Y/n]
```

3. I run `xxh server +vv +hh /tmp/xxh` with above config.
output:

```
server:/tmp/xxh/.xxh/shells/xxh-shell-zsh not found. Install xxh-shell-zsh? [Y/n]
```

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Good catch! Thanks!
