### ISSUE TITLE
+q option in config file does not take effect

### ISSUE THREAD

**Issue by chitoku-k** [xxh/xxh#93]
**Local OS (where xxh is installed):**
macOS 10.15.5

**Destination host OS:**
CentOS 8.1.1911

**xxh version:**
0.8.3

**xxh-plugins installed:**
xxh-shell-zsh

**config:**
```yaml
hosts:
  ".*":
    +q
```

**Steps to Reproduce**
1. I run `xxh myhost` with the config
2. The output log:
```
Install xxh-shell-zsh to apricot:/home/chitoku/.xxh
Remove apricot:/home/chitoku/.xxh
First time upload using rsync (this will be omitted on the next connections)
First run xxh-shell-zsh on apricot
```
3. What is the problem
The option `+q` did not take effect because `self.quiet` does not get applied after config is loaded whilst `self.verbose` and `self.vverbose` are applied then. Related to #89.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
@chitoku-k thanks! Please check it out from master:
```
pip install -U git+https://github.com/xxh/xxh
xxh myhost
```

**Comment by chitoku-k** [comment]
@anki-code Thanks for your quick fix! It now works as expected in master.
