### ISSUE TITLE
xxh message "Install sshpass to using password"

### ISSUE THREAD

**Issue by jms257** [xxh/xxh#99]
I'm having some difficulty getting xxh to work.  I can successfully ssh into a server (prompts for password and then connects me), but when I replace 'ssh' with 'xxh', it prompts for the password and then after supplied, prints the following message and does not leave me connected:
"Install sshpass to using password: https://duckduckgo.com/?q=install+sshpass  
Note! There are a lot of security reasons to stop using password auth."

Is this suggesting that xxh doesn't work with password authentication? 

Edit:
Sorry, I suppose I should include some other information.

**Local OS (where xxh is installed):**
Ubuntu 20.04.1

**Destination host OS:**
Fedora 30 (server edition)

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hey @jms257! It works! Just install ssh pass:
```bash
sudo apt install sshpass
xxh myhost                                  # password prompt will be shown
xxh myhost +P 'password'           # without password prompt (but it's not secure and not recommended in the world)
```

**Comment by jms257** [comment]
Hi @anki-code, I do really like the idea of xxh, but if "xxh myhost +P 'password'" is the only way to use password authentication, I'll not be using it since it's so insecure.  Is there any other way to use xxh and password authentication?

**Comment by anki-code** [comment]
@jms257 what you expect as password authentication? By default ssh ask password typing and this case is supporting by xxh as I wrote above. Just run `xxh myhost` and you'll see the prompt. Or if you mean another way to pass the password please tell about it.

If you mean the question in the background about why you need to install `sshpass` then it used to avoid typing password many times. During process xxh sends around 5 commands and to avoid typing password five times we use `sshpass`.

**Comment by jms257** [comment]
Ah, I understand now.  You most recent edit including the "or" made it more clear.  So sshpass is essentially a dependency for xxh if we want to use password authentication.  It seems to be working now, thanks!
